
// "candidate_name": "Nilesh kumar",
// "candidate_email": "rasdvahsd@gmail.com",
// "candidate_number":  "9005552324",
// "source": "linkdin",
// "previous_organization": "na",
// "referral_employee_email": "yafay@gmail.com",
// "skill": "na",
// "total_exp": "na",
// "NP": "na",
// "status": "na",
// "isjoin": false,
// "offered": false,
// "dropped": false,